apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-api
  namespace: ml-system-dev
spec:
  selector:
    matchLabels:
      app: ml-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s