global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/prometheus_rules.yml

scrape_configs:
  - job_name: 'robot_pipeline'
    static_configs:
      - targets: ['robot-agent:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'robot-agent:9100'
